Repository AIN-T/tiggle-backend, pull requests merged in 2024-11, with the labels that each got.

#2 [Feat] like 테이블 추가
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/JpaLikeRepository.java
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/LikeEntity.java
  src/main/java/com/gamja/tiggle/like/domain/Like.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/Entity/ProgramEntity.java
  src/main/java/com/gamja/tiggle/user/adapter/out/persistence/UserEntity.java
Labels: feature

#8 [Refactor] 좋아요 테이블 이름 변경
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/LikeEntity.java
Labels: refactor

#9 [Feat] 메인페이지 카테고리 정렬 & 페이징처리 [#6]
  src/main/java/com/gamja/tiggle/program/adapter/in/web/ReadProgramController.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/JpaProgramRepository.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/ProgramPersistenceAdapter.java
  src/main/java/com/gamja/tiggle/program/application/port/out/ReadProgramPort.java
  src/main/java/com/gamja/tiggle/program/application/service/ReadProgramService.java
Labels: 💚 feature, 💜 backend

#10 [Feat] 프로그램 좋아요 기능 구현
  src/main/java/com/gamja/tiggle/common/BaseResponseStatus.java
  src/main/java/com/gamja/tiggle/like/adapter/in/web/CreateLikeController.java
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/JpaLikeRepository.java
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/LikeEntity.java
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/LikePersistenceAdapter.java
  src/main/java/com/gamja/tiggle/like/application/port/in/CreateLikeCommand.java
  src/main/java/com/gamja/tiggle/like/application/port/in/CreateLikeUseCase.java
  src/main/java/com/gamja/tiggle/like/application/port/out/LikePort.java
  src/main/java/com/gamja/tiggle/like/application/service/CreateLikeService.java
Labels: 💚 feature, 💜 backend

#11 [Feat] 공연 검색 기능 구현 [#7]
  src/main/java/com/gamja/tiggle/common/BaseResponseStatus.java
  src/main/java/com/gamja/tiggle/program/adapter/in/web/ReadProgramController.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/JpaProgramRepository.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/ProgramPersistenceAdapter.java
  src/main/java/com/gamja/tiggle/program/application/port/in/ReadProgramCommand.java
  src/main/java/com/gamja/tiggle/program/application/port/in/ReadProgramUseCase.java
  src/main/java/com/gamja/tiggle/program/application/port/out/ReadProgramPort.java
  src/main/java/com/gamja/tiggle/program/application/service/ReadProgramService.java
Labels: 💚 feature, 💜 backend

#13 [Refactor] 프로그램 상세 조회 시 좋아요 여부 구현 [#12]
  src/main/java/com/gamja/tiggle/program/adapter/in/web/ReadProgramController.java
  src/main/java/com/gamja/tiggle/program/adapter/in/web/response/GetProgramDetailResponse.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/ProgramPersistenceAdapter.java
  src/main/java/com/gamja/tiggle/program/application/port/in/ReadProgramUseCase.java
  src/main/java/com/gamja/tiggle/program/application/port/out/ReadProgramPort.java
  src/main/java/com/gamja/tiggle/program/application/service/ReadProgramService.java
  src/main/java/com/gamja/tiggle/program/domain/Program.java
Labels: 💚 feature, ❤️ refactor, 💜 backend

#14 [Feat] 나의 좋아요 목록 조회 기능 구현 [#4]
  src/main/java/com/gamja/tiggle/like/adapter/in/web/ReadLikeController.java
  src/main/java/com/gamja/tiggle/like/adapter/in/web/response/ReadMyLikeResponse.java
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/JpaLikeRepository.java
  src/main/java/com/gamja/tiggle/like/adapter/out/persistence/LikePersistenceAdapter.java
  src/main/java/com/gamja/tiggle/like/application/port/in/ReadLikeCommand.java
  src/main/java/com/gamja/tiggle/like/application/port/in/ReadLikeUseCase.java
  src/main/java/com/gamja/tiggle/like/application/port/out/LikePort.java
  src/main/java/com/gamja/tiggle/like/application/service/ReadLikeService.java
Labels: 💚 feature, 💜 backend

#15 [Feat] 구역별 잔여좌석 조회 구현 [#3]
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/GetSectionController.java
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/response/GetSectionListResponse.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/Entity/SectionEntity.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/GetSectionAdapter.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/Response/GetSectionResponse.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/repositroy/SectionRepository.java
  src/main/java/com/gamja/tiggle/reservation/domain/Section.java
Labels: 💚 feature, 💜 backend

#16 [Refactor] 프로그램 상세 조회 수정
  src/main/java/com/gamja/tiggle/program/adapter/in/web/ReadProgramController.java
  src/main/java/com/gamja/tiggle/program/adapter/in/web/response/GetProgramDetailResponse.java
  src/main/java/com/gamja/tiggle/program/adapter/out/persistence/ProgramPersistenceAdapter.java
  src/main/java/com/gamja/tiggle/program/domain/Program.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/repositroy/SectionRepository.java
Labels: ❤️ refactor, 💜 backend

#18 [Refactor] 동시성 제어를 위한 redis 도입 [#17]
  build.gradle
  src/main/java/com/gamja/tiggle/config/RedisConfig.java
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/GetSectionController.java
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/VerifySeatController.java
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/request/VerifySeatRequest.java
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/response/VerifySeatResponse.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/GetSeatAdapter.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/GetSectionAdapter.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/SaveReservationAdapter.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/repositroy/SectionRepository.java
  src/main/java/com/gamja/tiggle/reservation/application/port/in/GetSectionUseCase.java
  src/main/java/com/gamja/tiggle/reservation/application/port/in/VerifySeatCommand.java
  src/main/java/com/gamja/tiggle/reservation/application/port/out/GetSeatPort.java
  src/main/java/com/gamja/tiggle/reservation/application/port/out/GetSectionPort.java
  src/main/java/com/gamja/tiggle/reservation/application/port/out/SaveReservationPort.java
  src/main/java/com/gamja/tiggle/reservation/application/service/GetSectionService.java
  src/main/java/com/gamja/tiggle/reservation/application/service/VerifySeatService.java
  src/main/resources/application.yml
Labels: wontfix, ❤️ refactor, 💜 backend

#19 [Refactor] Redis 연동을 통한 임시 예매 내역 조회 로직 개선
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/ReadReservationController.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/ReadReservationPersistenceAdapter.java
  src/main/java/com/gamja/tiggle/reservation/application/port/in/ReadReservationUseCase.java
  src/main/java/com/gamja/tiggle/reservation/application/port/in/ReadTemporaryReservationCommand.java
  src/main/java/com/gamja/tiggle/reservation/application/port/out/ReadReservationPort.java
  src/main/java/com/gamja/tiggle/reservation/application/service/ReadReservationService.java
Labels: 💚 feature, ❤️ refactor, 💜 backend

#20 [Refactor] 누락된 변수 추가
  src/main/java/com/gamja/tiggle/reservation/adapter/in/web/ReadReservationController.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/ReadReservationPersistenceAdapter.java
Labels: ❤️ refactor, 💜 backend

#21 [Refactor] 좌석 예약 동시성 제어 강화를 위한 Redis 분산 락 및 Atomic Operation 도입 [#17]
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/GetSeatAdapter.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/GetSectionAdapter.java
  src/main/java/com/gamja/tiggle/reservation/adapter/out/persistence/SaveReservationAdapter.java
  src/main/java/com/gamja/tiggle/reservation/application/port/out/SaveReservationPort.java
Labels: ❤️ refactor, 💜 backend
